# __Date and TimeDelta in Pandas__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:

- Date and TimeDelta in Pandas
- Date Handling in Pandas
  * Extracting Components from Dates
- Timedelta in Pandas
  * Creating a Timedelta
  * Performing Arithmetic Operations
  * Resampling Time Series Data

##  __1. Date and TimeDelta in Pandas__

In Pandas, the datetime module provides robust functionality for handling date and time data, while the timedelta class allows for convenient manipulation of time intervals. This combination is particularly useful for time-based analysis and working with temporal data in a DataFrame.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/3_Date_and_TimeDelta_in_Pandas/Date_and_Time.png)

## __2. Date Handling in Pandas__
#### Creating a Date Range:

- The date_range function is used to generate a sequence of dates within a specified range.
- It is a powerful tool for creating time indices or date columns in a DataFrame.
- The start and end parameters define the range, while freq determines the frequency, such as daily (D) or monthly (M).

In [1]:
import pandas as pd

# Generate a date range
date_range = pd.date_range(start='2023-01-01', end='2027-01-10', freq='m')
print(date_range)

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31',
               '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[ns]', freq='ME')

C:\Users\Deepak Pandey\AppData\Local\Temp\ipykernel_22812\2916418175.py:4: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  date_range = pd.date_range(start='2023-01-01', end='2027-01-10', freq='m')

In [2]:
first_day_of_month = date_range.to_period('m').to_timestamp()
first_day_of_month

C:\Users\Deepak Pandey\AppData\Local\Temp\ipykernel_22812\2228878345.py:1: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'M' instead.
  first_day_of_month = date_range.to_period('m').to_timestamp()

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01',
               '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01',
               '2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01',
               '2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01'],
              dtype='datetime64[ns]', freq='MS')

### __2.1 Extracting Components from Dates__

Pandas provides the dt accessor to extract various components (Example: day, month, year) from a date column in a DataFrame. This is valuable for time-based analysis when specific date attributes need to be considered.

In [3]:
import pandas as pd

# Assuming 'df' is your DataFrame with a 'Date' column
data = {'Date': ['2023-01-01', '2023-02-15', '2023-03-20']}
df = pd.DataFrame(data)



df['Date'] = pd.to_datetime(df['Date'])
print(df)

        Date
0 2023-01-01
1 2023-02-15
2 2023-03-20

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 156.0 bytes

In [5]:
# Extracting day, month, and year information
df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

# Displaying the DataFrame with extracted information
print(df[['Date', 'Day', 'Month', 'Year']])

        Date  Day  Month  Year
0 2023-01-01    1      1  2023
1 2023-02-15   15      2  2023
2 2023-03-20   20      3  2023

In [6]:
# Extracting weekday and weekend information
df = pd.DataFrame({'Date': pd.date_range(start='2024-08-31', periods=15,freq="d")})
df['Weekday'] = df['Date'].dt.weekday
df['IsWeekend'] = df['Date'].dt.weekday // 5 == 1
(df[['Date', 'Weekday', 'IsWeekend']])

         Date  Weekday  IsWeekend
0  2024-08-31        5       True
1  2024-09-01        6       True
2  2024-09-02        0      False
3  2024-09-03        1      False
4  2024-09-04        2      False
5  2024-09-05        3      False
6  2024-09-06        4      False
7  2024-09-07        5       True
8  2024-09-08        6       True
9  2024-09-09        0      False
10 2024-09-10        1      False
11 2024-09-11        2      False
12 2024-09-12        3      False
13 2024-09-13        4      False
14 2024-09-14        5       True

In [7]:
# Shifting dates forward or backward

df['Date'] = pd.to_datetime(df['Date'])
df['PreviousDate'] = df['Date'] - pd.Timedelta(days=1)
df['NextDate'] = df['Date'] + pd.Timedelta(days=1)
(df[[ 'PreviousDate','Date','NextDate']])

   PreviousDate       Date   NextDate
0    2024-08-30 2024-08-31 2024-09-01
1    2024-08-31 2024-09-01 2024-09-02
2    2024-09-01 2024-09-02 2024-09-03
3    2024-09-02 2024-09-03 2024-09-04
4    2024-09-03 2024-09-04 2024-09-05
5    2024-09-04 2024-09-05 2024-09-06
6    2024-09-05 2024-09-06 2024-09-07
7    2024-09-06 2024-09-07 2024-09-08
8    2024-09-07 2024-09-08 2024-09-09
9    2024-09-08 2024-09-09 2024-09-10
10   2024-09-09 2024-09-10 2024-09-11
11   2024-09-10 2024-09-11 2024-09-12
12   2024-09-11 2024-09-12 2024-09-13
13   2024-09-12 2024-09-13 2024-09-14
14   2024-09-13 2024-09-14 2024-09-15

In [8]:
# Performing arithmetic operations with timedeltas
df['Date'] = pd.to_datetime(df['Date'])
df['FutureDate'] = df['Date'] + pd.Timedelta(weeks=2, days=3, hours=12)
(df[['Date', 'FutureDate']])

         Date          FutureDate
0  2024-08-31 2024-09-17 12:00:00
1  2024-09-01 2024-09-18 12:00:00
2  2024-09-02 2024-09-19 12:00:00
3  2024-09-03 2024-09-20 12:00:00
4  2024-09-04 2024-09-21 12:00:00
5  2024-09-05 2024-09-22 12:00:00
6  2024-09-06 2024-09-23 12:00:00
7  2024-09-07 2024-09-24 12:00:00
8  2024-09-08 2024-09-25 12:00:00
9  2024-09-09 2024-09-26 12:00:00
10 2024-09-10 2024-09-27 12:00:00
11 2024-09-11 2024-09-28 12:00:00
12 2024-09-12 2024-09-29 12:00:00
13 2024-09-13 2024-09-30 12:00:00
14 2024-09-14 2024-10-01 12:00:00

## __3. Timedelta in Pandas__
### __3.1 Creating a Timedelta__

- The Timedelta class in Pandas represents a duration or the difference between two dates or times.
- It can be created by specifying the desired duration, such as days, hours, or minutes.

In [9]:
import pandas as pd
import numpy as np

data = {
    'Date': pd.date_range(start='2023-01-01', periods=100, freq='H'),
    'Profit': np.random.randint(10, 20, size=100),
    'Sales':np.random.randint(2000, 3000, size=100)
}
df = pd.DataFrame(data)

C:\Users\Deepak Pandey\AppData\Local\Temp\ipykernel_22812\2420486708.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  'Date': pd.date_range(start='2023-01-01', periods=100, freq='H'),

In [10]:
df

                  Date  Profit  Sales
0  2023-01-01 00:00:00      12   2163
1  2023-01-01 01:00:00      15   2379
2  2023-01-01 02:00:00      11   2767
3  2023-01-01 03:00:00      11   2195
4  2023-01-01 04:00:00      14   2611
..                 ...     ...    ...
95 2023-01-04 23:00:00      14   2116
96 2023-01-05 00:00:00      15   2371
97 2023-01-05 01:00:00      13   2966
98 2023-01-05 02:00:00      19   2563
99 2023-01-05 03:00:00      15   2360

[100 rows x 3 columns]

In [11]:
(19+17+15+15)/4

16.5

### __3.2 Performing Arithmetic Operations__

Timedelta objects can be used to perform arithmetic operations on dates. For example, adding a timedelta to a date results in a new date. This is useful for calculating future or past dates based on a given time interval.

In [12]:
# Performing arithmetic operations with timedeltas
df['Date'] = pd.to_datetime(df['Date'])
df['FutureDate'] = df['Date'] + pd.Timedelta(weeks=2, days=3, hours=12)
print(df[['Date', 'FutureDate']])

                  Date          FutureDate
0  2023-01-01 00:00:00 2023-01-18 12:00:00
1  2023-01-01 01:00:00 2023-01-18 13:00:00
2  2023-01-01 02:00:00 2023-01-18 14:00:00
3  2023-01-01 03:00:00 2023-01-18 15:00:00
4  2023-01-01 04:00:00 2023-01-18 16:00:00
..                 ...                 ...
95 2023-01-04 23:00:00 2023-01-22 11:00:00
96 2023-01-05 00:00:00 2023-01-22 12:00:00
97 2023-01-05 01:00:00 2023-01-22 13:00:00
98 2023-01-05 02:00:00 2023-01-22 14:00:00
99 2023-01-05 03:00:00 2023-01-22 15:00:00

[100 rows x 2 columns]

### __3.3 Resampling Time Series Data__

Time series data often comes with irregular time intervals. Resampling is the process of changing the frequency of the time series data, either by upsampling (increasing frequency) or downsampling (decreasing frequency).

In [13]:
# Resampling time series data
df.set_index('Date', inplace=True)

df_resampled = df.resample('M').mean()
(df_resampled)

C:\Users\Deepak Pandey\AppData\Local\Temp\ipykernel_22812\2376966547.py:4: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_resampled = df.resample('M').mean()

            Profit    Sales                    FutureDate
Date
2023-01-31   14.81  2507.01 2023-01-20 13:30:00.000000256